version: "3.8"

services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DATABASE_URL=postgresql://fepa:fepa123@fepa-postgres:5432/fepa_blog
      - RABBITMQ_URL=amqp://fepa:fepa123@fepa-rabbitmq:5672
    networks:
      - fepa-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  fepa-network:
    name: api-gateway_fepa-network
    external: true

volumes:
  postgres_data:
  rabbitmq_data:
