version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: fepa_blog_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fepa_blog
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fepa_blog_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5051:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
